---

Layout/LineContinuationLeadingSpace:
  Enabled: false

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

require:
  - rubocop-rake
  - rubocop-minitest
  - rubocop-performance

Layout/LineLength:
  Max: 80
