---

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

require:
  - rubocop-minitest
  - rubocop-performance

Layout/LineLength:
  Max: 80
Style/StringConcatenation:
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: false
