#!/usr/bin/env ruby

require_relative 'lib/controller'
require_relative 'lib/config_loader'

abort 'supply a zone name' if ARGV.empty?

zname = ARGV.first

conf = ZoneManager::ConfigLoader.new("#{zname}.yaml")

zone = ZoneManager::Controller.new(zname)

conf.write_config

zone.teardown
zone.configure
zone.install
zone.boot
