inherit_from:
  - ../.rubocop.yml

Metrics/AbcSize:
  Max: 100
Metrics/MethodLength:
  Max: 50
Metrics/BlockLength:
  Max: 50
Metrics/ClassLength:
  Max: 150
Layout/LineContinuationLeadingSpace:
  Enabled: false
